model_embeddings:
  model: "nomic-embed-text"

llm_model:
  model: "llama3.2:3b"
  temperature: 0.5
  top_p: 0.1
  streaming: false

small_llm_model:

retriever:
  topk: 3

chromavectordb:
  batch_size: 128
