llm_model:
  num_ctx: 4096
  temperature: 0.3

small_llm_model:
  model: "llama3.2:3b"
  temperature: 1

retriever:
  topk: 10

reranker:
  model: "ms-marco-MultiBERT-L-12"
  topk: 5
  score_threshold: 0.5
